name: defect-detection
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - appnope=0.1.0
  - astor=0.7.1
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - cctools=895
  - certifi=2019.6.16
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - cloudpickle=1.2.1
  - compiler-rt=4.0.1
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask-core=2.1.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - freetype=2.9.1
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.56.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - keras=2.1.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld64=274.2
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libtiff=4.0.10
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - ptyprocess=0.6.0
  - pycocotools=2.0.0
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywavelets=1.0.3
  - pyyaml=5.1.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.2
  - readline=7.0
  - scikit-image=0.15.0
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - theano=1.0.3
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - opencv-python==4.1.0.25

